name: monorepo

services:
  backend:
    build:
      context: .                        # root = context supaya bisa akses packages/shared
      dockerfile: apps/backend/Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      FRONTEND_URL: ${FRONTEND_URL}
      DATABASE_URL: ${DATABASE_URL}
      DB_AUTH_TOKEN: ${DB_AUTH_TOKEN}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      SESSION_SECRET: ${SESSION_SECRET}
      API_KEY: ${API_KEY}

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
